services:
  # Public Frontend PWA
  frontend-public:
    build:
      context: ./frontend-public
      dockerfile: Dockerfile
      target: development
    ports:
      - "3443:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
      - REACT_APP_ENV=development
      - CHOKIDAR_USEPOLLING=true # useful for hot reload with bind mounts
      - HTTPS=true
      - SSL_CRT_FILE=/app/certs/cert.pem
      - SSL_KEY_FILE=/app/certs/key.pem
    volumes:
      - ./frontend-public:/app
      - ./frontend-public/certs:/app/certs:ro
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - art-detection-network

  # Administrators' Dashboard
  frontend-admin:
    build:
      context: ./frontend-admin
      dockerfile: Dockerfile
      target: development
    ports:
      - "4443:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
      - REACT_APP_ENV=development
      - CHOKIDAR_USEPOLLING=true # useful for hot reload with bind mounts
      - HTTPS=true
      - SSL_CRT_FILE=/app/certs/cert.pem
      - SSL_KEY_FILE=/app/certs/key.pem
    volumes:
      - ./frontend-admin:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - art-detection-network

  # Backend API using Python FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    environment:
      - HF_HOME=/app/cache
    volumes:
      - ./backend:/app
      - ./backend/cache:/app/cache
    networks:
      - art-detection-network
    depends_on:
      - weaviate

  # Vector Database for similarity search (optional)
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.0
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    networks:
      - art-detection-network

networks:
  art-detection-network:
    driver: bridge

volumes:
  weaviate_data:
